### ISSUE TITLE
1.Release - Texto centrado-arriba de un color solido

### ISSUE THREAD

**Issue by Javiview** [Javiview/Practica_9_GIT_DAW_J_AGUDO#2]
Añadir al html: index.html un texto que ponga: "GIT MASTER" con las siguientes caracteristicas:
- h1
- class="text-master"

**Comment by JoseMaSerranoMaroto** [comment]
Tarea finalizada

**Comment by JoseMaSerranoMaroto** [comment]
Tarea finalizada
